name: Build AirDrop17

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks

      - name: Build AirDrop17
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: AirDrop17-deb
          path: packages/*.deb
          if-no-files-found: error
